### ISSUE TITLE
0.4.0 Breaks when using Using Build Agent nuget.exe

### ISSUE THREAD

**Issue by dustinchilson** [cake-build/cake-vso#55] opened 2020-02-27 12:56 UTC
### What You Are Seeing?
When using `0.4.0` and `useBuildAgentNuGetExe: true`

We receive the error `The term 'Get-ToolPath' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

### What version of Cake are you using?
0.4.0

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Hosted? Custom?
OnPrem Custom

### Output Log

~~~sh
2020-02-27T12:33:43.8882749Z ##[section]Starting: Use NuGet >=4.9.4
2020-02-27T12:33:43.9117705Z ==============================================================================
2020-02-27T12:33:43.9118495Z Task         : NuGet tool installer
2020-02-27T12:33:43.9119680Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
2020-02-27T12:33:43.9120767Z Version      : 0.164.0
2020-02-27T12:33:43.9121342Z Author       : Microsoft Corporation
2020-02-27T12:33:43.9122235Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0
2020-02-27T12:33:43.9123259Z ==============================================================================
2020-02-27T12:33:44.5777110Z You are using a query match on the version string. Behavior changes or breaking changes might occur as NuGet updates to a new version.
2020-02-27T12:33:44.7103202Z Found tool in cache: NuGet 5.4.0 x64
2020-02-27T12:33:44.7104212Z Using version: 5.4.0
2020-02-27T12:33:44.7107699Z Found tool in cache: NuGet 5.4.0 x64
2020-02-27T12:33:44.7108460Z Using tool path: D:\Agent.1\_tool\NuGet\5.4.0\x64
2020-02-27T12:33:44.7116183Z Prepending PATH environment variable with directory: D:\Agent.1\_tool\NuGet\5.4.0\x64
2020-02-27T12:33:44.7299268Z ##[section]Finishing: Use NuGet >=4.9.4
2020-02-27T12:33:44.7364773Z ##[section]Starting: NuGet restore
2020-02-27T12:33:44.7596974Z ==============================================================================
2020-02-27T12:33:44.7597735Z Task         : NuGet
2020-02-27T12:33:44.7599149Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2020-02-27T12:33:44.7600612Z Version      : 2.164.0
2020-02-27T12:33:44.7601168Z Author       : Microsoft Corporation
2020-02-27T12:33:44.7601992Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
2020-02-27T12:33:44.7602899Z ==============================================================================
2020-02-27T12:33:45.9161733Z SYSTEMVSSCONNECTION exists true
2020-02-27T12:33:46.0437189Z SYSTEMVSSCONNECTION exists true
2020-02-27T12:33:46.9015968Z [command]C:\Windows\system32\chcp.com 65001
2020-02-27T12:33:46.9227873Z Active code page: 65001
2020-02-27T12:33:46.9946003Z Detected NuGet version 5.4.0.6315 / 5.4.0+d790b66be476cd901a56bd46ada037162097ee21.d790b66be476cd901a56bd46ada037162097ee21
2020-02-27T12:33:46.9977524Z SYSTEMVSSCONNECTION exists true
2020-02-27T12:33:47.0120461Z [command]D:\Agent.1\_tool\NuGet\5.4.0\x64\nuget.exe restore D:\Agent.1\491\s\apps\Services\Api\SalesPad.Spo.Api.Server.All.sln -Verbosity Quiet -NonInteractive -ConfigFile D:\Agent.1\491\s\NuGet.Config
2020-02-27T12:34:02.2712181Z ##[section]Finishing: NuGet restore
2020-02-27T12:34:02.2779718Z ##[section]Starting: Build
2020-02-27T12:34:02.3009065Z ==============================================================================
2020-02-27T12:34:02.3009816Z Task         : Cake
2020-02-27T12:34:02.3010318Z Description  : Build with Cake
2020-02-27T12:34:02.3010835Z Version      : 0.4.0
2020-02-27T12:34:02.3011342Z Author       : Patrik Svensson
2020-02-27T12:34:02.3012118Z Help         : [More Information about Cake](https://cakebuild.net)
2020-02-27T12:34:02.3012986Z ==============================================================================
2020-02-27T12:34:03.3399970Z Using Build Agent nuget.exe
2020-02-27T12:34:03.6910910Z ##[error]The term 'Get-ToolPath' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
~~~

**Comment by gep13** [comment] 2020-02-27 13:13
@dustinchilson thanks for reporting this.  This looks to be a duplicate of this issue:

https://github.com/cake-build/cake-vso/issues/56

I am going to go ahead and close out this issue.  If you would like to subscribe to the other issue, and add any additional information that you think would be useful, we can continue over there.

**Closed as completed by gep13** 2020-02-27 13:13 UTC
Labels: duplicate
