### ISSUE TITLE
Doesn't pull modules into build

### ISSUE THREAD

**Issue by charlessolar** [cake-build/cake-vso#40] opened 2017-05-29 14:06 UTC
Using the marketplace cake build it doesn't seem to pull the modules from `modules/packages.config` as was added here: https://github.com/cake-build/resources/issues/26

Using powershell or bash to run cake works

(discovered in #39)

**Comment by agc93** [comment] 2017-05-31 01:48
Duplicate of #37 

This one's on my todo list, but just hadn't got a chance yet :disappointed: 

I'll hopefully get something working soon!

**EDIT**: Also you can use the workaround outlined in #37 to restore packages and still use the "proper" Cake task.

**Closed as completed by agc93** 2017-05-31 01:48 UTC
